name: Auto Fetch News

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Manual trigger button

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # <-- IMPORTANT for push access

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run News Scraper
        run: python scrapers/newsapi_scraper.py

      - name: Commit & Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add news.db
          git commit -m "Auto-fetch latest news" || echo "No changes to commit"
          git push origin main
