name: Auto Fetch News

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (UTC)
  workflow_dispatch:  # Allows manual run from GitHub Actions UI

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run News Scraper
      run: |
        python scrapers/newsapi_scraper.py

    - name: Commit & Push Changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add news.db
        git commit -m "Auto-fetch latest news"
        git push
      continue-on-error: true  # Avoid failure if no new articles
